# Load numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
a.ndim

1

In [10]:
b = np.array([[2,3,4],[5,6,7]], dtype = 'int16')
print(b)

[[2 3 4]
 [5 6 7]]


In [22]:
b.ndim

2

In [7]:
b.shape

(2, 3)

In [11]:
b.dtype

dtype('int16')

In [12]:
b.itemsize

2

In [13]:
print(b)

[[2 3 4]
 [5 6 7]]


In [15]:
#get element
b[0, 2]

4

In [20]:
#get row
c = b[1,:]

In [21]:
print(c)

[5 6 7]


In [19]:
#get coloumn
b[:, 0]

array([2, 5], dtype=int16)

In [22]:
#slicing
b[0, 1]

3

### replacing the value

In [86]:
print(b)

[[83 45 88]
 [ 4  4  4]]


In [89]:
b[:,1] = 6

In [90]:
print(b)

[[83  6 88]
 [ 4  6  4]]


In [83]:
b[:, :]

array([[83, 45, 88],
       [69, 51,  4]])

In [29]:
#reshaping array
c = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])

In [30]:
c.shape

(4, 3)

In [56]:
c.reshape(3, 4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

## Mathematics

In [31]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [63]:
c + 2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [64]:
c - 2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
c*2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [33]:
c/3

array([[0.66666667, 1.        , 1.33333333],
       [1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333],
       [3.66666667, 4.        , 4.33333333]])

In [66]:
c.sum()

90

In [36]:
d = np.array([3,4,5])
d

array([3, 4, 5])

In [37]:
a + d

array([4, 6, 8])

In [76]:
a / d

array([0.33333333, 0.5       , 0.6       ])

In [77]:
d**2

array([ 9, 16, 25], dtype=int32)

In [81]:
print(c)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [39]:
c.sum(axis=0)

array([26, 30, 34])

## Statistics

In [40]:
print(b)

[[2 3 4]
 [5 6 4]]


In [41]:
np.min(b)

2

In [42]:
np.max(b)

6

In [43]:
np.mean(b)

4.0

In [45]:
np.std(b)

1.2909944487358056

In [46]:
np.sqrt(b)

array([[1.4142135, 1.7320508, 2.       ],
       [2.236068 , 2.4494898, 2.       ]], dtype=float32)

## Linear Algebra

In [60]:
a = np.ones((2,3))
print(a)
a.shape

[[1. 1. 1.]
 [1. 1. 1.]]


(2, 3)

In [61]:
b = np.random.randint(15, 100, size = (2,3))
print(b)

[[83 45 88]
 [69 51 46]]


In [62]:
a*b

array([[83., 45., 88.],
       [69., 51., 46.]])

In [66]:
o = np.vstack([a,b,a])
print(o)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [83. 45. 88.]
 [69. 51. 46.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [69]:
p = np.hstack([a,b,b])
print(p)
p.shape

[[ 1.  1.  1. 83. 45. 88. 83. 45. 88.]
 [ 1.  1.  1. 69. 51. 46. 69. 51. 46.]]


(2, 9)

In [70]:
e = np.array([1,2,3,4])

In [107]:
np.exp(e)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [71]:
np.log(p)

array([[0.        , 0.        , 0.        , 4.41884061, 3.80666249,
        4.47733681, 4.41884061, 3.80666249, 4.47733681],
       [0.        , 0.        , 0.        , 4.2341065 , 3.93182563,
        3.8286414 , 4.2341065 , 3.93182563, 3.8286414 ]])

In [72]:
np.log10(p)

array([[0.        , 0.        , 0.        , 1.91907809, 1.65321251,
        1.94448267, 1.91907809, 1.65321251, 1.94448267],
       [0.        , 0.        , 0.        , 1.83884909, 1.70757018,
        1.66275783, 1.83884909, 1.70757018, 1.66275783]])

In [73]:
t = np.ones((3,3))
print(t)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [76]:
t[1,2] = 4
print(t)

[[1. 1. 1.]
 [1. 4. 4.]
 [1. 1. 1.]]


In [11]:
np.random.rand(3,3)

array([[0.74232962, 0.40175779, 0.32044046],
       [0.69986221, 0.79384736, 0.68785511],
       [0.52689258, 0.338966  , 0.61654422]])

In [13]:
np.random.randint(1,7, size=(3,3))

array([[5, 2, 4],
       [6, 5, 3],
       [2, 3, 3]])

In [77]:
np.identity((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
r = np.ones((5,5))
s = np.zeros((3,3))
#print(r)

s[1,1] = 9
#print(s)

r[1:4, 1:4] = s

print(r)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
a = np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [103]:
b = np.array([[9,9,9], [9,9,9,], [9,9,9]])
print(b)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [105]:
a[0:3, 0:3] = b
print(a)

[[9. 9. 9. 1.]
 [9. 9. 9. 1.]
 [9. 9. 9. 1.]
 [1. 1. 1. 1.]]


In [107]:
a[2,1:3] = 0
print(a)

[[9. 9. 9. 1.]
 [9. 9. 9. 1.]
 [9. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [110]:
a[1:3, 2] = 0
print(a)

[[9. 9. 9. 1.]
 [9. 9. 0. 1.]
 [9. 0. 0. 1.]
 [1. 1. 1. 1.]]
